// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileMoneyTutorial.Models;

namespace MobileMoneyTutorial.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("MobileMoneyTutorial.Models.ConfirmationResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillRefNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessShortCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MSISDN")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgAccountBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThirdPartyTransID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
